
DROP TABLE IF EXISTS Kat_mp CASCADE;
DROP TABLE IF EXISTS Kategoria CASCADE;
DROP TABLE IF EXISTS Muistilista CASCADE;
DROP TABLE IF EXISTS Muistiinpano CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
